apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: swagger
  namespace: ubisoft
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: swagger
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 75